[package]
name = "switch-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packet = {path = "./packet"}
log = "0.4.17"
log4rs = "1.2.0"
dirs = "4.0.0"
dashmap = "5.4.0"
crossbeam = "0.8.2"
parking_lot = "0.12.1"

rsa = "0.7.2"
rand = "0.8.5"
sha2 ={version="0.10.6",features=["oid"]}
colored = "2.0.0"

thiserror = "1.0.37"
chrono = "0.4.23"
lazy_static = "1.4.0"
moka = "0.9.6"
protobuf = "3.2.0"
[build-dependencies]
protobuf-codegen = "3.2.0"
protoc-bin-vendored = "3.0.0"