[package]
name = "vnts"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packet = {path = "./packet"}
clap = { version = "4.0.32", features = ["derive"] }
log = "0.4.17"
log4rs = "1.2.0"
dirs = "4.0.0"
dashmap = "5.4.0"
crossbeam = "0.8.2"
parking_lot = "0.12.1"

rsa = "0.7.2"
rand = "0.8.5"
sha2 ={version="0.10.6",features=["oid"]}
colored = "2.0.0"

thiserror = "1.0.37"
chrono = "0.4.23"
lazy_static = "1.4.0"
moka = "0.9.6"
protobuf = "3.2.0"
tokio = { version = "1.28.1", features = ["full"] }
async-trait = "0.1.71"
tokio-util = { version = "0.7.8", features = ["full"] }
[build-dependencies]
protobuf-codegen = "3.2.0"
protoc-bin-vendored = "3.0.0"